// Daily briefing cron — Track B refactor.
// Schedule: 0 9 * * 1-5 (UTC) = 06:00 BRT, Mon-Fri.
// URL preserved as /api/cron/morning-briefing so existing unsubscribe links
// continue to work. Body now generated by email-engine/generators/dailyBriefing.

import { NextRequest, NextResponse } from "next/server";
import { createClient, type User } from "@supabase/supabase-js";
import { verifyCronAuthDetailed } from "@/lib/macro/cron-auth";
import { isAdminRequest } from "@/lib/macro/admin-trigger";
import { acquireCronLock } from "@/lib/cron-lock";
import { logCronRun } from "@/lib/cron-log";
import { buildUnsubscribeUrl } from "@/lib/email/unsubscribe-token";
import { send } from "@/email-engine/integrations/resend";
import {
  generateDailyBriefing,
  buildDailyBriefingProps,
} from "@/email-engine/generators/dailyBriefing";
import { isBrHoliday } from "@/email-engine/data/holidays-br";
import type { Plan } from "@/email-engine/__mocks__/types";

export const runtime = "nodejs";
export const maxDuration = 60;

const APP_URL = process.env.NEXT_PUBLIC_APP_URL ?? "https://owealthinvesting.com";

function brasiliaDateStr(offsetDays = 0): string {
  const parts = new Intl.DateTimeFormat("en-CA", {
    timeZone: "America/Sao_Paulo",
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
  }).formatToParts(new Date(Date.now() + offsetDays * 86400000));
  const y = parts.find((p) => p.type === "year")!.value;
  const m = parts.find((p) => p.type === "month")!.value;
  const d = parts.find((p) => p.type === "day")!.value;
  return `${y}-${m}-${d}`;
}

function planFromSub(plan: string | undefined): Plan {
  if (plan === "pro") return "pro";
  if (plan === "elite" || plan === "ultra" || plan === "mentor") return "ultra";
  return "free";
}

export async function GET(req: NextRequest) {
  return logCronRun("morning-briefing", () => handle(req));
}

export async function POST(req: NextRequest) {
  return logCronRun("morning-briefing", () => handle(req));
}

async function handle(req: NextRequest) {
  const auth = verifyCronAuthDetailed(req);
  let viaAdmin = false;
  if (!auth.ok) {
    if (auth.reason === "invalid_auth" && (await isAdminRequest(req))) {
      viaAdmin = true;
    } else {
      console.error("[morning-briefing] auth failed:", auth.reason);
      if (auth.reason === "missing_secret") {
        return NextResponse.json(
          { ok: false, error: "CRON_SECRET not configured on server" },
          { status: 503 },
        );
      }
      return NextResponse.json({ ok: false, error: "Unauthorized" }, { status: 401 });
    }
  }

  if (!viaAdmin && !(await acquireCronLock("morning-briefing"))) {
    return NextResponse.json({ ok: true, skipped: "lock_held" });
  }

  const testEmail = req.nextUrl.searchParams.get("test_email");
  const dryRun = req.nextUrl.searchParams.get("dry_run") === "true";

  // Skip weekends
  const utcDay = new Date().getUTCDay();
  if (!testEmail && !viaAdmin && (utcDay === 0 || utcDay === 6)) {
    return NextResponse.json({ ok: true, skipped: "weekend", utcDay });
  }

  const todayStr = brasiliaDateStr(0);

  // Skip BR national holidays
  if (!testEmail && !viaAdmin && isBrHoliday(todayStr)) {
    return NextResponse.json({ ok: true, skipped: "holiday", date: todayStr });
  }

  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!supabaseUrl || !serviceKey) {
    return NextResponse.json({ ok: false, error: "Missing Supabase config" }, { status: 500 });
  }
  const supabase = createClient(supabaseUrl, serviceKey);

  // Generate the shared payload once.
  let payload;
  try {
    payload = await generateDailyBriefing(new Date());
  } catch (err) {
    const message = err instanceof Error ? err.message : "unknown";
    console.error("[morning-briefing] generateDailyBriefing failed:", message);
    return NextResponse.json({ ok: false, error: `generator: ${message}` }, { status: 500 });
  }

  // Paginate users.
  const allUsers: User[] = [];
  for (let page = 1; page <= 50; page++) {
    const { data, error } = await supabase.auth.admin.listUsers({ perPage: 1000, page });
    if (error || !data) {
      return NextResponse.json({ ok: false, error: "Failed to list users" }, { status: 500 });
    }
    allUsers.push(...data.users);
    if (data.users.length < 1000) break;
  }

  const users = testEmail ? allUsers.filter((u) => u.email === testEmail) : allUsers;
  if (testEmail && users.length === 0) {
    return NextResponse.json({ ok: false, error: `User not found: ${testEmail}` }, { status: 404 });
  }

  // Opt-outs (RFC 8058 sink).
  const { data: optOuts } = await supabase.from("email_opt_outs").select("email");
  const optOutSet = new Set<string>(
    (optOuts ?? []).map((o: { email: string }) => o.email.toLowerCase()),
  );

  // Per-channel opt-in flag.
  const { data: profileFlags } = await supabase
    .from("profiles")
    .select("id, briefing_enabled, preferred_locale");
  const briefingEnabledMap = new Map<string, boolean>();
  const localeMap = new Map<string, "pt" | "en">();
  for (const p of profileFlags ?? []) {
    briefingEnabledMap.set(p.id, p.briefing_enabled !== false);
    if (p.preferred_locale === "en") localeMap.set(p.id, "en");
  }

  // Plans.
  const { data: subs } = await supabase
    .from("subscriptions")
    .select("user_id, plan, status");
  const subMap = new Map<string, string>();
  for (const sub of subs ?? []) {
    if (sub.status === "active" || sub.status === "trialing") {
      subMap.set(sub.user_id, sub.plan);
    }
  }

  let sent = 0;
  const skipReasons: Record<string, number> = {
    no_email: 0,
    banned: 0,
    opted_out: 0,
    flag_off: 0,
    send_failed: 0,
  };

  // Batches of 100, throttle between to stay under Resend's 10 req/s.
  const BATCH = 100;
  const eligible = users.filter((u) => {
    if (!u.email) {
      skipReasons.no_email++;
      return false;
    }
    if (u.banned_until && new Date(u.banned_until) > new Date()) {
      skipReasons.banned++;
      return false;
    }
    if (optOutSet.has(u.email.toLowerCase())) {
      skipReasons.opted_out++;
      return false;
    }
    if (briefingEnabledMap.get(u.id) === false) {
      skipReasons.flag_off++;
      return false;
    }
    return true;
  });

  for (let i = 0; i < eligible.length; i += BATCH) {
    const batch = eligible.slice(i, i + BATCH);
    const results = await Promise.allSettled(
      batch.map(async (user) => {
        const email = user.email!;
        const plan = planFromSub(subMap.get(user.id));
        const unsubscribeUrl = buildUnsubscribeUrl(email);
        const props = buildDailyBriefingProps({
          payload,
          unsubscribeUrl,
          appUrl: APP_URL,
          plan,
        });

        if (dryRun) return { ok: true, dryRun: true };

        const r = await send({
          template: "daily-briefing",
          props,
          to: email,
        });

        // Audit log.
        await supabase.from("email_logs").insert({
          user_id: user.id,
          template: "daily-briefing",
          to_email: email,
          status: r.ok ? "sent" : "failed",
          error: r.ok ? null : r.error ?? "send failed",
        });

        return r;
      }),
    );

    for (const res of results) {
      if (res.status === "fulfilled" && (res.value as { ok: boolean }).ok) {
        sent++;
      } else {
        skipReasons.send_failed++;
      }
    }

    // Throttle between batches.
    if (i + BATCH < eligible.length) {
      await new Promise((r) => setTimeout(r, 1000));
    }
  }

  return NextResponse.json({
    ok: true,
    totalUsers: allUsers.length,
    eligible: eligible.length,
    sent,
    skipped: skipReasons,
    payload: {
      date: payload.date,
      marketBias: payload.marketBias,
      eventCount: payload.today.length,
    },
    dryRun,
  });
}
