// app/app/macro/page.tsx
"use client";

import dynamic from "next/dynamic";
import { useState, useEffect, useCallback, useRef, useMemo } from "react";
import { useMyAssets } from "@/hooks/useMyAssets";
import { MyAssetsFilter, useMyAssetsToggle } from "@/components/macro/MyAssetsFilter";
import { useAppT } from "@/hooks/useAppLocale";
import { Globe, RefreshCw, CalendarDays, FileText, AlertTriangle, Clock } from "lucide-react";

// Relocated from /app home (C-05) — compact macro widgets above the full terminal.
const MacroWidgetBriefing = dynamic(
  () => import("@/components/macro/MacroWidgetBriefing").then((m) => ({ default: m.MacroWidgetBriefing })),
  { ssr: false, loading: () => <div className="h-[200px] w-full rounded-xl bg-muted animate-pulse" /> },
);
const MacroWidgetEvents = dynamic(
  () => import("@/components/macro/MacroWidgetEvents").then((m) => ({ default: m.MacroWidgetEvents })),
  { ssr: false, loading: () => <div className="h-[200px] w-full rounded-xl bg-muted animate-pulse" /> },
);
import { Button } from "@/components/ui/button";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { PaywallGate } from "@/components/billing/PaywallGate";
import { LiveIndicator } from "@/components/macro/LiveIndicator";
import { AdaptiveAlerts } from "@/components/macro/AdaptiveAlerts";
import { HeadlinesFeed } from "@/components/macro/HeadlinesFeed";
import { EconomicCalendar } from "@/components/macro/EconomicCalendar";
import { WeeklyBriefing } from "@/components/macro/WeeklyBriefing";
import { InterestRatesPanel } from "@/components/macro/InterestRatesPanel";
import { WeeklyHistory } from "@/components/macro/WeeklyHistory";
import { SentimentCard } from "@/components/macro/SentimentCard";
import { supabase } from "@/lib/supabase/client";
import { getWeekStart } from "@/lib/macro/constants";
import type { EconomicEvent, WeeklyPanorama, CentralBankRate, AdaptiveAlert as AdaptiveAlertType, MacroHeadline } from "@/lib/macro/types";

export default function MacroIntelligencePage() {
  const t = useAppT();
  const [events, setEvents] = useState<EconomicEvent[]>([]);
  const [panorama, setPanorama] = useState<WeeklyPanorama | null>(null);
  const [rates, setRates] = useState<CentralBankRate[]>([]);
  const [alerts, setAlerts] = useState<AdaptiveAlertType[]>([]);
  const [headlines, setHeadlines] = useState<MacroHeadline[]>([]);
  const [weeks, setWeeks] = useState<{ week_start: string; week_end: string }[]>([]);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [showRefreshDialog, setShowRefreshDialog] = useState(false);
  const [hasUnseenReport, setHasUnseenReport] = useState(false);
  const [headlinesRefreshing, setHeadlinesRefreshing] = useState(false);
  const [toastMsg, setToastMsg] = useState<string | null>(null);
  const [activeTab, setActiveTab] = useState<"terminal" | "report">("terminal");

  // Widgets (MacroWidgetEvents / MacroWidgetBriefing) dispatch this to
  // navigate the user to the matching tab + anchor within the same page.
  useEffect(() => {
    function handleSwitch(e: Event) {
      const detail = (e as CustomEvent<{ tab?: "terminal" | "report"; anchor?: string }>).detail;
      if (detail?.tab) setActiveTab(detail.tab);
      if (detail?.anchor) {
        // Wait a tick for tab content to mount before scrolling.
        requestAnimationFrame(() => {
          document.getElementById(detail.anchor!)?.scrollIntoView({
            behavior: "smooth",
            block: "start",
          });
        });
      }
    }
    window.addEventListener("macro:switch-tab", handleSwitch as EventListener);
    return () => window.removeEventListener("macro:switch-tab", handleSwitch as EventListener);
  }, []);

  // Week navigation: on weekends show next week's briefing (already generated by cron)
  const defaultWeek = (() => {
    const now = new Date();
    const day = now.getDay();
    if (day === 0 || day === 6) {
      const daysUntilMonday = day === 0 ? 1 : 2;
      const nextMonday = new Date(now);
      nextMonday.setDate(now.getDate() + daysUntilMonday);
      return getWeekStart(nextMonday);
    }
    return getWeekStart();
  })();
  const [calendarWeek, setCalendarWeek] = useState(defaultWeek);

  // [C-10] My-assets filter: narrow feeds to currencies of user-traded symbols.
  const myAssets = useMyAssets();
  const [myAssetsEnabled, setMyAssetsEnabled] = useMyAssetsToggle();
  const activeCurrencies = useMemo(() => new Set(myAssets.currencies), [myAssets.currencies]);
  const activeCountries = useMemo(() => new Set(myAssets.countries), [myAssets.countries]);
  const filteredEvents = useMemo(() => {
    if (!myAssetsEnabled || activeCurrencies.size === 0) return events;
    return events.filter((e) => {
      if (e.currency && activeCurrencies.has(e.currency)) return true;
      if (e.country && activeCountries.has(e.country)) return true;
      return false;
    });
  }, [events, myAssetsEnabled, activeCurrencies, activeCountries]);
  const filteredRates = useMemo(() => {
    if (!myAssetsEnabled || activeCountries.size === 0) return rates;
    return rates.filter((r) => activeCountries.has(r.country));
  }, [rates, myAssetsEnabled, activeCountries]);
  const filteredHeadlines = useMemo(() => {
    if (!myAssetsEnabled || (myAssets.symbols.length === 0 && activeCurrencies.size === 0)) {
      return headlines;
    }
    const needles = [...myAssets.symbols, ...Array.from(activeCurrencies)].map((s) => s.toUpperCase());
    return headlines.filter((h) => {
      const text = `${h.headline} ${h.summary ?? ""}`.toUpperCase();
      return needles.some((n) => text.includes(n));
    });
  }, [headlines, myAssetsEnabled, myAssets.symbols, activeCurrencies]);

  // Helper to safely parse JSON from a fetch result
  const safeJson = useCallback(async (result: PromiseSettledResult<Response>) => {
    if (result.status === "rejected") return { ok: false };
    try { return await result.value.json(); } catch { return { ok: false }; }
  }, []);

  // Helper to parse JSONB string fields from panorama
  const parsePanoramaFields = useCallback((pan: Record<string, unknown>) => {
    const jsonbFields = ["regional_analysis", "decision_intelligence", "sentiment", "market_impacts", "asset_impacts"];
    for (const field of jsonbFields) {
      if (typeof pan[field] === "string") {
        try { pan[field] = JSON.parse(pan[field] as string); } catch { pan[field] = null; }
      }
    }
    return pan;
  }, []);

  // PERF-004: Fetch calendar data separately (depends on calendarWeek)
  const fetchCalendar = useCallback(async () => {
    try {
      const calRes = await fetch(`/api/macro/calendar?week=${calendarWeek}`);
      const calJson = await calRes.json();
      if (calJson.ok) setEvents(calJson.data || []);
    } catch (error) {
      console.error("[macro] Failed to fetch calendar:", error);
    }
  }, [calendarWeek]);

  // PERF-004: Fetch non-calendar data separately (depends only on mount/defaultWeek)
  const fetchGlobalData = useCallback(async () => {
    try {
      const [panRes, ratesRes, alertsRes, histRes, hdlRes] = await Promise.allSettled([
        fetch(`/api/macro/panorama?week=${defaultWeek}`),
        fetch("/api/macro/rates"),
        fetch(`/api/macro/alerts?week=${defaultWeek}`),
        fetch("/api/macro/history"),
        fetch("/api/macro/headlines?limit=15"),
      ]);

      const [panJson, ratesJson, alertsJson, histJson, hdlJson] = await Promise.all([
        safeJson(panRes),
        safeJson(ratesRes),
        safeJson(alertsRes),
        safeJson(histRes),
        safeJson(hdlRes),
      ]);

      if (panJson.ok && panJson.data) {
        parsePanoramaFields(panJson.data);
        const pan = panJson.data as WeeklyPanorama;
        setPanorama(pan);

        // Check if panorama was updated since last seen
        try {
          const lastSeen = localStorage.getItem("lastSeenPanoramaUpdate");
          if (lastSeen && pan.updated_at && new Date(pan.updated_at) > new Date(lastSeen)) {
            setHasUnseenReport(true);
          } else if (!lastSeen && pan.updated_at) {
            setHasUnseenReport(true);
          }
        } catch { /* ignore localStorage errors */ }
      }
      if (ratesJson.ok) setRates(ratesJson.data || []);
      if (alertsJson.ok) setAlerts(alertsJson.data || []);
      if (hdlJson.ok) setHeadlines(hdlJson.data || []);
      if (histJson.ok) setWeeks(histJson.data || []);
    } catch (error) {
      console.error("[macro] Failed to fetch global data:", error);
    }
  }, [defaultWeek, safeJson, parsePanoramaFields]);

  // Combined fetchData for manual refresh and initial load
  const fetchData = useCallback(async () => {
    try {
      await Promise.all([fetchCalendar(), fetchGlobalData()]);
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  }, [fetchCalendar, fetchGlobalData]);

  // Initial load: fetch everything
  useEffect(() => {
    fetchData();

    // Safety timeout: force loading=false after 10s to prevent infinite spinner
    const safetyTimeout = setTimeout(() => {
      setLoading((prev) => {
        if (prev) console.warn("[macro] Safety timeout: forcing loading=false after 10s");
        return false;
      });
    }, 10_000);
    return () => clearTimeout(safetyTimeout);
  // Run once on mount — fetchData is intentionally omitted to prevent
  // re-fetching when its useCallback dependencies change. Week changes
  // are handled by the separate effect below.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // PERF-004: Re-fetch only calendar when week changes (skip on initial mount)
  const isInitialMount = useRef(true);
  useEffect(() => {
    if (isInitialMount.current) {
      isInitialMount.current = false;
      return;
    }
    fetchCalendar();
  }, [fetchCalendar]);


  const REFRESH_COOLDOWN_KEY = "macro_last_full_refresh";
  const REFRESH_COOLDOWN_MS = 24 * 60 * 60 * 1000; // 24h

  const getLastRefreshTime = (): number => {
    try { return parseInt(localStorage.getItem(REFRESH_COOLDOWN_KEY) || "0", 10); }
    catch { return 0; }
  };

  const handleRefreshClick = () => {
    setShowRefreshDialog(true);
  };

  const handleRefreshConfirm = async () => {
    setShowRefreshDialog(false);

    const lastRefresh = getLastRefreshTime();
    const now = Date.now();
    if (now - lastRefresh < REFRESH_COOLDOWN_MS) {
      const hoursAgo = Math.round((now - lastRefresh) / (60 * 60 * 1000));
      setToastMsg(`Atualização já realizada há ${hoursAgo}h. Aguarde 24h entre atualizações.`);
      return;
    }

    setRefreshing(true);
    try {
      const { data: { session } } = await supabase.auth.getSession();
      if (!session) return;

      const headers = { Authorization: `Bearer ${session.access_token}` };

      // Run rates first (fast, ~10s), calendar in background (can be slow)
      const ratesResult = await Promise.race([
        fetch("/api/macro/refresh-rates", { method: "POST", headers }),
        new Promise<Response>((_, reject) => setTimeout(() => reject(new Error("timeout")), 55000)),
      ]).catch(() => null);

      if (ratesResult && ratesResult.ok) {
        console.log("[macro] Rates refreshed successfully");
      }

      // Refresh data immediately after rates (user sees updated rates fast)
      await fetchData();

      // Calendar refresh in background (don't block UI)
      fetch("/api/macro/refresh-calendar", { method: "POST", headers })
        .then(async (res) => {
          if (res.ok) {
            console.log("[macro] Calendar refreshed, reloading data...");
            await fetchData(); // Auto-refresh page with new calendar data
          }
        })
        .catch((err) => console.warn("[macro] Calendar refresh failed:", err));

      localStorage.setItem(REFRESH_COOLDOWN_KEY, String(Date.now()));
    } catch (err) {
      console.error("[macro] Full refresh failed:", err);
    } finally {
      setRefreshing(false);
    }
  };

  // Calendar-specific refresh (fetches latest from Faireconomy)
  const handleCalendarRefresh = useCallback(async () => {
    const { data: { session } } = await supabase.auth.getSession();
    if (!session) return;

    // Determine if we need the next-week URL
    const nextWeekDate = new Date();
    nextWeekDate.setDate(nextWeekDate.getDate() + 7);
    const nextWeek = getWeekStart(nextWeekDate);
    const weekParam = calendarWeek === nextWeek ? "next" : "";

    const url = weekParam
      ? `/api/macro/refresh-calendar?week=${weekParam}`
      : "/api/macro/refresh-calendar";

    const res = await fetch(url, {
      method: "POST",
      headers: { Authorization: `Bearer ${session.access_token}` },
    });
    const json = await res.json();
    if (!json.ok) {
      console.error("[macro] Calendar refresh failed:", json.error);
    }

    // Re-fetch calendar data to show updated values
    const calRes = await fetch(`/api/macro/calendar?week=${calendarWeek}`);
    try {
      const calJson = await calRes.json();
      if (calJson.ok) setEvents(calJson.data || []);
    } catch { /* ignore */ }
  }, [calendarWeek]);

  // Auto-sync calendar when current week has no data (cron hasn't run yet)
  const autoSyncTriggered = useRef(false);
  useEffect(() => {
    if (autoSyncTriggered.current) return;
    if (calendarWeek !== defaultWeek) return;
    if (loading) return;
    if (events.length > 0) return;

    autoSyncTriggered.current = true;
    console.log("[macro] No events for current week, auto-syncing calendar...");
    handleCalendarRefresh().catch((err) =>
      console.warn("[macro] Auto calendar sync failed:", err)
    );
  }, [loading, events.length, calendarWeek, defaultWeek, handleCalendarRefresh]);

  // Track if regeneration is in progress (shared between manual + auto)
  const regeneratingRef = useRef(false);
  const [isRegenerating, setIsRegenerating] = useState(false);

  // Reset regeneration guard on mount (prevents stuck state from previous page load)
  useEffect(() => {
    regeneratingRef.current = false;
  }, []);

  // Regenerate weekly report via Claude
  const handleRegenerate = useCallback(async () => {
    // Prevent concurrent regenerations
    if (regeneratingRef.current) {
      console.log("[macro] Regeneration already in progress, skipping");
      return;
    }

    const { data: { session } } = await supabase.auth.getSession();
    if (!session) {
      console.warn("[macro] No session found, cannot regenerate");
      setToastMsg("Sessão expirada. Faça login novamente.");
      return;
    }

    regeneratingRef.current = true;
    setIsRegenerating(true);
    console.log("[macro] Starting regeneration for week:", defaultWeek);

    try {
      const controller = new AbortController();
      const timeoutId = setTimeout(() => controller.abort(), 55000); // 55s client timeout

      const res = await fetch("/api/macro/regenerate-report", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${session.access_token}`,
        },
        body: JSON.stringify({ week: defaultWeek }),
        signal: controller.signal,
      });
      clearTimeout(timeoutId);

      if (!res.ok) {
        const json = await res.json().catch(() => ({ error: `Erro HTTP ${res.status}` }));
        console.error("[macro] Regenerate failed:", res.status, json);
        setToastMsg(json.error || "Erro ao regenerar relatório");
        return;
      }

      const json = await res.json();
      if (!json.ok) {
        console.error("[macro] Regenerate returned not ok:", json);
        setToastMsg(json.error || "Erro ao regenerar relatório");
        return;
      }

      console.log("[macro] Regeneration succeeded:", json);
    } catch (err) {
      const error = err as Error;
      if (error.name === "AbortError") {
        console.error("[macro] Regeneration timed out after 55s");
        setToastMsg("Timeout — a geração demorou mais de 55 segundos. Tente novamente.");
      } else {
        console.error("[macro] Regeneration error:", error);
        setToastMsg("Erro de conexão ao regenerar. Tente novamente.");
      }
      return;
    } finally {
      regeneratingRef.current = false;
      setIsRegenerating(false);
    }

    // Refetch panorama to show updated data
    try {
      const panRes = await fetch(`/api/macro/panorama?week=${defaultWeek}`);
      const panJson = await panRes.json();
      if (panJson.ok && panJson.data) {
        const pan = panJson.data;
        if (typeof pan.regional_analysis === "string") {
          try { pan.regional_analysis = JSON.parse(pan.regional_analysis); } catch { pan.regional_analysis = null; }
        }
        if (typeof pan.decision_intelligence === "string") {
          try { pan.decision_intelligence = JSON.parse(pan.decision_intelligence); } catch { pan.decision_intelligence = null; }
        }
        if (typeof pan.sentiment === "string") {
          try { pan.sentiment = JSON.parse(pan.sentiment); } catch { pan.sentiment = null; }
        }
        if (typeof pan.market_impacts === "string") {
          try { pan.market_impacts = JSON.parse(pan.market_impacts); } catch { pan.market_impacts = null; }
        }
        if (typeof pan.asset_impacts === "string") {
          try { pan.asset_impacts = JSON.parse(pan.asset_impacts); } catch { pan.asset_impacts = null; }
        }
        setPanorama(pan);
      }
    } catch { /* ignore */ }
  }, [defaultWeek]);

  // Headlines manual refresh — force live fetch to bypass stale DB cache
  const handleHeadlinesRefresh = useCallback(async () => {
    setHeadlinesRefreshing(true);
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), 20_000);
    try {
      const { data: { session } } = await supabase.auth.getSession();
      const headers: Record<string, string> = {};
      if (session?.access_token) {
        headers.Authorization = `Bearer ${session.access_token}`;
      }
      const res = await fetch("/api/macro/headlines?limit=30&live=1", {
        headers,
        signal: controller.signal,
      });
      const json = await res.json();
      if (json.ok) setHeadlines(json.data || []);
    } catch (err) {
      if ((err as Error).name !== "AbortError") {
        console.error("[macro] Headlines refresh failed:", err);
      }
    } finally {
      clearTimeout(timeout);
      setHeadlinesRefreshing(false);
    }
  }, []);

  // Mark report as seen when Report tab is selected
  const handleReportTabClick = useCallback(() => {
    setHasUnseenReport(false);
    if (panorama?.updated_at) {
      try {
        localStorage.setItem("lastSeenPanoramaUpdate", panorama.updated_at);
      } catch { /* ignore */ }
    }
  }, [panorama?.updated_at]);

  // Handle week change from calendar navigation
  const handleWeekChange = useCallback(async (newWeek: string) => {
    setCalendarWeek(newWeek);
    // Fetch calendar events for the new week
    try {
      const calRes = await fetch(`/api/macro/calendar?week=${newWeek}`);
      const calJson = await calRes.json();
      if (calJson.ok) setEvents(calJson.data || []);
    } catch {
      setEvents([]);
    }
  }, []);

  // Silent regenerate for auto-refresh (no alerts, no blocking manual clicks)
  const silentRegenerate = useCallback(async () => {
    const { data: { session } } = await supabase.auth.getSession();
    if (!session) return;

    try {
      const controller = new AbortController();
      const timeoutId = setTimeout(() => controller.abort(), 55000);

      const res = await fetch("/api/macro/regenerate-report", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${session.access_token}`,
        },
        body: JSON.stringify({ week: defaultWeek }),
        signal: controller.signal,
      });
      clearTimeout(timeoutId);

      if (!res.ok) {
        console.warn("[macro] Auto-regenerate failed:", res.status);
        return;
      }

      const json = await res.json();
      if (!json.ok) {
        console.warn("[macro] Auto-regenerate returned not ok:", json.error);
        return;
      }

      console.log("[macro] Auto-regenerate succeeded, refreshing panorama...");
      // Refetch panorama silently
      const panRes = await fetch(`/api/macro/panorama?week=${defaultWeek}`);
      const panJson = await panRes.json();
      if (panJson.ok && panJson.data) {
        const pan = panJson.data;
        if (typeof pan.asset_impacts === "string") {
          try { pan.asset_impacts = JSON.parse(pan.asset_impacts); } catch { pan.asset_impacts = null; }
        }
        setPanorama(pan);
      }
    } catch (err) {
      console.warn("[macro] Auto-regenerate error:", err);
    }
  }, [defaultWeek]);

  // Auto-refresh daily update if stale (>4 hours old)
  const dailyRefreshTriggered = useRef(false);
  useEffect(() => {
    if (!panorama?.asset_impacts?.daily_update_at || dailyRefreshTriggered.current) return;

    const lastUpdate = new Date(panorama.asset_impacts.daily_update_at);
    const hoursSince = (Date.now() - lastUpdate.getTime()) / (1000 * 60 * 60);

    if (hoursSince >= 4) {
      dailyRefreshTriggered.current = true;
      console.log(`[macro] Daily update is ${Math.round(hoursSince)}h old, auto-regenerating silently...`);
      silentRegenerate().catch((err) =>
        console.warn("[macro] Auto daily update failed:", err)
      );
    }
  }, [panorama?.asset_impacts?.daily_update_at, silentRegenerate]);

  // Auto-poll headlines every 30 minutes (PERF-005: skip when tab is hidden)
  useEffect(() => {
    const POLL_INTERVAL = 30 * 60 * 1000; // 30 minutes

    const pollHeadlines = () => {
      if (document.visibilityState !== "visible") return;
      fetch("/api/macro/headlines?limit=30&live=1")
        .then((res) => res.json())
        .then((data) => {
          if (data.ok && data.data) {
            setHeadlines(data.data);
          }
        })
        .catch(console.error);
    };

    const interval = setInterval(pollHeadlines, POLL_INTERVAL);
    return () => clearInterval(interval);
  }, []);

  // Poll for actual values during market hours (Mon-Fri, 12:00-22:00 UTC)
  const pollRef = useRef<ReturnType<typeof setInterval> | null>(null);
  useEffect(() => {
    // Only poll when viewing current week
    if (calendarWeek !== defaultWeek) return;

    pollRef.current = setInterval(() => {
      // PERF-005: Skip polling when tab is hidden
      if (document.visibilityState !== "visible") return;
      const now = new Date();
      const day = now.getUTCDay();
      const hour = now.getUTCHours();
      // Mon-Fri, 12:00-22:00 UTC covers major market hours
      if (day >= 1 && day <= 5 && hour >= 12 && hour <= 22) {
        handleCalendarRefresh();
      }
    }, 5 * 60 * 1000); // 5 minutes

    return () => {
      if (pollRef.current) clearInterval(pollRef.current);
    };
  }, [calendarWeek, defaultWeek, handleCalendarRefresh]);

  if (loading) {
    return (
      <div className="mx-auto max-w-6xl px-6 py-10">
        <div className="space-y-4">
          {[...Array(4)].map((_, i) => (
            <div
              key={i}
              className="h-32 animate-pulse rounded-[22px]"
              style={{ backgroundColor: "hsl(var(--card))" }}
            />
          ))}
        </div>
      </div>
    );
  }

  return (
    <div className="w-full max-w-none px-4 sm:px-6 lg:px-8 py-8 h-full flex flex-col">
      {/* Header */}
      <div className="mb-6 flex flex-col md:flex-row md:items-end justify-between gap-4 shrink-0">
        <div>
          <div className="flex items-center gap-3 mb-1">
            <Globe className="h-6 w-6 text-blue-500" />
            <h1 className="text-3xl font-display font-bold tracking-tight text-foreground">{t("macro.title")}</h1>
            <LiveIndicator />
          </div>
          <p className="text-sm text-muted-foreground font-medium">{t("macro.subtitle")}</p>
        </div>
        <div className="flex flex-wrap items-center gap-2">
          <MyAssetsFilter
            enabled={myAssetsEnabled}
            onToggle={setMyAssetsEnabled}
            currencies={myAssets.currencies}
            loading={myAssets.loading}
          />
          <Button
            variant="outline"
            size="sm"
            onClick={handleRefreshClick}
            disabled={refreshing}
            className="gap-2"
          >
            <RefreshCw className={`h-4 w-4 ${refreshing ? "animate-spin" : ""}`} />
            {refreshing ? t("macro.refreshing") : t("macro.refresh")}
          </Button>
        </div>
      </div>



      {/* Compact macro snapshot (relocated from /app home — C-05) */}
      <div className="mb-6 grid gap-4 md:grid-cols-2 shrink-0">
        <MacroWidgetBriefing />
        <MacroWidgetEvents />
      </div>

      {/* Confirmation Dialog */}
      <Dialog open={showRefreshDialog} onOpenChange={setShowRefreshDialog}>
        <DialogContent className="sm:max-w-md">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <AlertTriangle className="h-5 w-5 text-amber-500" />
              {t("macro.dialog.title")}
            </DialogTitle>
            <DialogDescription asChild>
              <div className="space-y-3 text-sm text-muted-foreground">
                <p>
                  {t("macro.dialog.body")}
                  <strong className="text-foreground"> {t("macro.dialog.limit")}</strong>
                </p>
                <div className="rounded-lg border border-border/60 p-3 space-y-1.5">
                  <p className="font-medium text-foreground text-xs uppercase tracking-widest">{t("macro.dialog.willUpdate")}</p>
                  <ul className="list-disc list-inside space-y-1">
                    <li>{t("macro.dialog.li1")}</li>
                    <li>{t("macro.dialog.li2")}</li>
                    <li>{t("macro.dialog.li3")}</li>
                  </ul>
                </div>
              </div>
            </DialogDescription>
          </DialogHeader>
          <DialogFooter className="gap-2 sm:gap-0">
            <Button variant="outline" onClick={() => setShowRefreshDialog(false)}>
              {t("macro.dialog.cancel")}
            </Button>
            <Button onClick={handleRefreshConfirm}>
              {t("macro.dialog.confirm")}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Inline toast */}
      {toastMsg && (
        <div className="w-full mb-4 flex items-center justify-between rounded-xl border border-destructive/30 bg-destructive/10 px-4 py-3">
          <p className="text-sm text-destructive font-medium">{toastMsg}</p>
          <button type="button" onClick={() => setToastMsg(null)} className="text-destructive/60 hover:text-destructive ml-3" aria-label={t("macro.toast.close")}>
            &times;
          </button>
        </div>
      )}

      {/* Empty state — macro data not yet loaded (before cron jobs run) */}
      {events.length === 0 && !panorama && rates.length === 0 && headlines.length === 0 && (
        <div className="mb-6 flex justify-center">
          <div
            className="flex flex-col items-center gap-4 rounded-[22px] border-2 border-dashed border-border/60 px-10 py-12 text-center max-w-md"
            style={{ backgroundColor: "hsl(var(--card))" }}
          >
            <div className="flex h-12 w-12 items-center justify-center rounded-full bg-muted/60">
              <Clock className="h-6 w-6 text-muted-foreground" />
            </div>
            <div>
              <h3 className="text-base font-semibold tracking-tight text-foreground">
                {t("macro.empty.title")}
              </h3>
              <p className="mt-1.5 text-sm text-muted-foreground leading-relaxed">
                {t("macro.empty.body")}
              </p>
            </div>
            <Button
              variant="outline"
              size="sm"
              onClick={() => { setRefreshing(true); fetchData(); }}
              disabled={refreshing}
              className="mt-2 gap-2"
            >
              <RefreshCw className={`h-4 w-4 ${refreshing ? "animate-spin" : ""}`} />
              {t("macro.empty.retry")}
            </Button>
          </div>
        </div>
      )}

      {/* Adaptive Alerts - Always visible */}
      {alerts.length > 0 && (
        <div className="w-full mb-6">
          <AdaptiveAlerts alerts={alerts} />
        </div>
      )}

      {/* Tabs */}
      <Tabs value={activeTab} onValueChange={(v) => setActiveTab(v as "terminal" | "report")} className="flex-1 flex flex-col min-h-0">
        <TabsList className="self-start mb-6 h-11">
          <TabsTrigger value="terminal" className="gap-2 px-4">
            <CalendarDays className="h-4 w-4" />
            {t("macro.tabs.terminal")}
          </TabsTrigger>
          <TabsTrigger value="report" className="gap-2 px-4 relative" onClick={handleReportTabClick}>
            <FileText className="h-4 w-4" />
            {t("macro.tabs.report")}
            {hasUnseenReport && (
              <span className="absolute -top-1 -right-1 h-2.5 w-2.5 rounded-full bg-blue-500 animate-pulse" />
            )}
          </TabsTrigger>
        </TabsList>

        {/* Tab 1: Terminal — Calendar, Rates */}
        {/* Terminal mode: Calendar full → Rates+Sentiment → Headlines+SemanaNumeros → History full. */}
        <TabsContent value="terminal" className="flex-1 min-h-0 mt-0">
          <div className="flex flex-col gap-4">
            {/* Row 1 — Calendar full width */}
            <section id="macro-calendar" className="flex flex-col rounded-[24px] border border-border/40 shadow-sm overflow-hidden relative isolate p-5 scroll-mt-24" style={{ backgroundColor: "hsl(var(--card))" }}>
              <h2 className="mb-3 text-[11px] font-semibold uppercase tracking-widest text-muted-foreground flex items-center gap-2">
                <span className="h-1.5 w-1.5 rounded-full bg-blue-500" />
                {t("macro.section.calendar")}
              </h2>
              <div className="flex-1 min-h-[400px]">
                <EconomicCalendar
                  events={filteredEvents}
                  weekStart={calendarWeek}
                  onWeekChange={handleWeekChange}
                  onRefresh={handleCalendarRefresh}
                />
              </div>
            </section>

            {/* Row 2 — Rates 2, Sentiment 1 */}
            <div className="grid gap-4 lg:grid-cols-3 items-stretch">
              <section className="lg:col-span-2 flex flex-col h-full rounded-[24px] border border-border/40 shadow-sm overflow-hidden relative isolate p-5" style={{ backgroundColor: "hsl(var(--card))" }}>
                <h2 className="mb-3 text-[11px] font-semibold uppercase tracking-widest text-muted-foreground flex items-center gap-2">
                  <span className="h-1.5 w-1.5 rounded-full bg-emerald-500" />
                  {t("macro.section.banks")}
                </h2>
                <div className="flex-1">
                  <PaywallGate requiredPlan="pro" blurContent>
                    <InterestRatesPanel rates={filteredRates} />
                  </PaywallGate>
                </div>
              </section>
              <div className="lg:col-span-1 h-full">
                <SentimentCard sentiment={panorama?.sentiment ?? null} />
              </div>
            </div>

            {/* Row 3 — Headlines 2, Semana em Números 1 */}
            <div className="grid gap-4 lg:grid-cols-3 items-stretch">
              <div className="lg:col-span-2 h-full">
                <HeadlinesFeed
                  headlines={filteredHeadlines}
                  onRefresh={handleHeadlinesRefresh}
                  refreshing={headlinesRefreshing}
                />
              </div>
              <section className="lg:col-span-1 flex flex-col h-full rounded-[24px] border border-border/40 shadow-sm p-5 isolate" style={{ backgroundColor: "hsl(var(--card))" }}>
                <h2 className="mb-3 text-[11px] font-semibold uppercase tracking-widest text-muted-foreground flex items-center gap-2">
                  <span className="h-1.5 w-1.5 rounded-full bg-rose-500" />
                  {t("macro.section.weekNumbers")}
                </h2>
                {(() => {
                  const high = filteredEvents.filter((e) => e.impact === "high").length;
                  const medium = filteredEvents.filter((e) => e.impact === "medium").length;
                  const countries = new Set(filteredEvents.map((e) => e.country)).size;
                  const rateCount = filteredRates.length;
                  return (
                    <dl className="grid flex-1 grid-cols-2 gap-3 text-sm">
                      <div className="rounded-xl border border-border/40 p-3">
                        <dt className="text-[10px] uppercase tracking-widest text-muted-foreground">{t("macro.kpi.highImpact")}</dt>
                        <dd className="mt-1 text-xl font-semibold text-red-500 tabular-nums">{high}</dd>
                      </div>
                      <div className="rounded-xl border border-border/40 p-3">
                        <dt className="text-[10px] uppercase tracking-widest text-muted-foreground">{t("macro.kpi.medium")}</dt>
                        <dd className="mt-1 text-xl font-semibold text-amber-500 tabular-nums">{medium}</dd>
                      </div>
                      <div className="rounded-xl border border-border/40 p-3">
                        <dt className="text-[10px] uppercase tracking-widest text-muted-foreground">{t("macro.kpi.countries")}</dt>
                        <dd className="mt-1 text-xl font-semibold text-foreground tabular-nums">{countries}</dd>
                      </div>
                      <div className="rounded-xl border border-border/40 p-3">
                        <dt className="text-[10px] uppercase tracking-widest text-muted-foreground">{t("macro.kpi.banks")}</dt>
                        <dd className="mt-1 text-xl font-semibold text-foreground tabular-nums">{rateCount}</dd>
                      </div>
                    </dl>
                  );
                })()}
              </section>
            </div>

            {/* Row 4 — History full width */}
            <section className="flex flex-col rounded-[24px] border border-border/40 shadow-sm p-5 isolate" style={{ backgroundColor: "hsl(var(--card))" }}>
              <h2 className="mb-3 text-[11px] font-semibold uppercase tracking-widest text-muted-foreground flex items-center gap-2">
                <span className="h-1.5 w-1.5 rounded-full bg-violet-500" />
                {t("macro.section.history")}
              </h2>
              <PaywallGate requiredPlan="pro" blurContent>
                <WeeklyHistory weeks={weeks} currentWeek={defaultWeek} />
              </PaywallGate>
            </section>
          </div>
        </TabsContent>

        {/* Tab 2: Relatório Macro — Full AI Report */}
        <TabsContent value="report" className="flex-1 min-h-0 mt-0">
          <div className="flex flex-col gap-6">
            {/* Weekly Briefing — expanded, no collapse */}
            <section id="macro-panorama" className="w-full rounded-[28px] border border-border/40 bg-card shadow-sm overflow-hidden relative isolate px-4 sm:px-6 py-5 scroll-mt-24" style={{ backgroundColor: "hsl(var(--card))" }}>
              <WeeklyBriefing panorama={panorama} onRegenerate={handleRegenerate} isRegenerating={isRegenerating} defaultExpanded />
            </section>

          </div>
        </TabsContent>
      </Tabs>
    </div>
  );
}
